openapi: 3.0.0
info:
  description: Openapiのサンプル
  title: API
  version: v1
servers:
- url: http://localhost:8082/
paths:
  /users:
    get:
      operationId: getUsers
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/user'
                type: array
          description: return user information
      summary: すべてのユーザーを取得する
      tags:
      - users
    post:
      operationId: addUser
      requestBody:
        content:
          application/json:
            example:
              name: 佐藤 二郎
              email: new@test.com
              example: qwertyudf123yuikassdc23
            schema:
              $ref: '#/components/schemas/user'
        description: ユーザー作成の引数
      responses:
        "201":
          description: CREATED
      summary: 新しいユーザーを追加する
      tags:
      - users
  /shops:
    get:
      operationId: getShops
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/shops'
          description: return shop information
      summary: すべての店舗情報を取得する
      tags:
      - shops
  /shops/{label}:
    get:
      operationId: getShops
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/shops'
          description: return shop information
      summary: すべての店舗情報を取得する
      tags:
      - shops
components:
  schemas:
    user:
      example:
        name: 山田 太郎
        label: qwertyudf123yuikassdc34
        email: test@test.com
      properties:
        name:
          description: ユーザーのフルネーム
          example: 山田 太郎
          type: string
        email:
          description: ユーザーのメールアドレス
          example: test@test.com
          type: string
        label:
          description: ユーザー情報のUID
          example: qwertyudf123yuikassdc34
          type: string
      required:
      - email
      - label
      - name
      type: object
    shops:
      items:
        $ref: '#/components/schemas/shop'
      type: array
    shop:
      example:
        images:
        - image.png
        - image2.png
        name: 山田整骨院
        options:
        - '{}'
        - '{}'
        logo: aaa.png
        label: qwertyudf123yuikassdc34
      properties:
        name:
          description: 店舗名
          example: 山田整骨院
          type: string
        logo:
          description: 店舗のロゴ
          example: aaa.png
          type: string
        label:
          description: 店舗情報のUID
          example: qwertyudf123yuikassdc34
          type: string
        images:
          description: HPのトップに表示する画像
          example:
          - image.png
          - image2.png
          items:
            type: string
          type: array
        options:
          description: HPに表示するボタンオプション
          items:
            properties:
              name:
                description: オプション名
                example: クーポン
                type: string
              url:
                description: オプションのURL or label
                example: http://test.com or wuh4fdiou3ioud9
                type: string
            required:
            - name
            - url
          type: array
      required:
      - images
      - label
      - logo
      - name
      - options
      type: object
