openapi: 3.0.0
info:
  title: API
  description: Openapiのサンプル
  version: v1

servers:
  # docker-composeでprismをホストしているポート番号に変更
  - url: http://localhost:8082/
paths:
  # ここに追加したいURL及び参照ファイルのrefを記載
  /users:
    $ref: './resources/path_info/users/root.yml'
  /users/current:
    $ref: './resources/path_info/users/current.yml'
  /shops:
    $ref: './resources/path_info/shops/root.yml'
components:
  # ここに追加したいentityの定義及び参照ファイルのrefを記載
  schemas:
    user:
      $ref: './resources/components/schemas/user.yml'
    shop:
      $ref: './resources/components/schemas/shop.yml'