openapi: 3.0.0
info:
  title: API
  description: Openapiのサンプル
  version: v1

servers:
  # docker-composeでprismをホストしているポート番号に変更
  - url: http://localhost:8082/
paths:
  # ここに追加したいURL及び参照ファイルのrefを記載
  /users:
    $ref: "./resources/path/users.yml"
  /shops:
    $ref: "./resources/path/shops.yml"
  /shops/{label}:
    $ref: "./resources/path/shops.yml"
